name: Automated release creation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 4"

jobs:
  release_management:
    uses: newrelic/coreint-automation/.github/workflows/reusable_release_automation.yaml@v4
    secrets: inherit
    with:
      rt-included-files: go.mod,go.sum,Dockerfile
