name: Release Packages

# Post-release task1: bump the version of this integration in the infrastructure-bundle image.
# Post-release task2: Bump bundle version on the make file and execute release-manifest workflow after new version of the infrastructure-bundle image is released.
on:
  release:
    types: [prereleased, released]

jobs:
  release-packages:
    name: Release tarball
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ amd64, arm64, arm ]
    env:
      S3_BASE_FOLDER: s3://nr-downloads-main/infrastructure_agent
      OS: linux
      ARCH: ${{ matrix.goarch }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate version from tag
        run: |
          RELEASE_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Validate tag and release version
        run: |
          echo "${{ github.event.release.tag_name }}" | grep -E '^v[0-9.]*[0-9]$'
          echo "$RELEASE_VERSION" | grep -E '^[0-9.]*[0-9]$'
      - if: ${{ github.event.release.prerelease }}
        run: |
          echo "S3_BASE_FOLDER=$S3_BASE_FOLDER/test" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Build tarball
        run: |
          make test
          make package_for OS=$OS ARCH=$ARCH RELEASE_VERSION=$RELEASE_VERSION
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.COREINT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.COREINT_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload tarball to https://download.newrelic.com
        run: |
          make release_tarball_package_for OS=$OS ARCH=$ARCH RELEASE_VERSION=$RELEASE_VERSION
